name: Mirroring

on: [push, delete]

jobs:
  to_notabug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@notabug.org:emacsfodder/emacs-theme-darktooth.git
          ssh_private_key:
            ${{ secrets.PRIVATE_KEY }}
