name: "Mirrored at notabug.org/emacsfodder/emacs-theme-darktooth"

on: [push, delete]

jobs:
  to_notabug:
    runs-on: ubuntu-latest
    env:
      notabug: "git@notabug.org:${{ env.GITHUB_REPOSITORY }}.git"
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          echo $notabug

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.notabug }}
          ssh_private_key:
            ${{ secrets.MIRROR_PUSH_KEY }}
